baseURL: https://swne.xyz/
languageCode: ko-kr
title: swne.xyz
theme: paper-mod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-5MG1FC3B0M

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: swne.xyz
  description: "Sungwon's Personal User Manual"
  keywords: [Blog, Portfolio]
  author: ssowonny 
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  # label:
  #   text: "Home"
  #   icon: /apple-touch-icon.png
  #   iconHeight: 35

  # profile-mode
  # profileMode:
  #   enabled: false # needs to be explicitly set
  #   title: ExampleSite
  #   subtitle: "This is subtitle"
  #   imageUrl: "<img location>"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: my image
  #   buttons:
  #     - name: Posts
  #       url: posts
  #     - name: Tags
  #       url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >
      #### Welcome to **Sungwon**'s personal user manual.

      - I've been working as a CPO at [Buzzvil](https://www.buzzvil.com) since 2021.
      I joined Buzzvil in July 2018 when it acquired my previous startup, 42 Company.
      Please visit [my Linkedin profile](https://www.linkedin.com/in/sungwon-lee-627a1448) to find out my work experience and skills.




  socialIcons:
    - name: twitter
      url: "https://twitter.com/@ssowonny"
    - name: facebook
      url: "https://www.facebook.com/ssowonny"
    - name: medium
      url: "https://medium.com/@ssowonny"
    - name: notion
      url: "https://ssowonny.notion.site/ssowonny-Lifelog-1bee3eda59214abc8001600c985852a6"
    - name: buzzvil
      url: "https://tech.buzzvil.com/author/whale-lee/"
    - name: github
      url: "https://github.com/ssowonny"
    - name: linkedin
      url: "https://www.linkedin.com/in/sungwon-lee-627a1448"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/ssowonny/swne.xyz/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
# menu:
#   main:
#     - identifier: career
#       name: career
#       url: /career
#       weight: 10
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 10
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai